export const projects = [
  {
    id: 'true-tech-team',
    title: 'True Tech Team',
    description: 'A home for all my side projects — built with Next.js and showcasing the tools, libraries, and experiments I build outside of work.',
    tags: ['Next.js', 'React', 'TypeScript'],
    image: '/images/true-tech-team.png',
    liveUrl: 'https://truetechteam.netlify.app/',
    githubUrl: null,
  },
  {
    id: 'component-library',
    title: 'React Component Library',
    description: '44+ production-ready React components with dark mode, 37 color families, and full Storybook documentation. Built to be the foundation for all my projects.',
    tags: ['React', 'TypeScript', 'SCSS', 'Storybook'],
    image: '/images/component-library.png',
    liveUrl: 'https://truetechteamcomponents.netlify.app/',
    githubUrl: null,
  },
  {
    id: 'codepen',
    title: 'CodePen Portfolio',
    description: 'A collection of UI experiments, CSS animations, and interactive components — where I prototype and explore creative ideas.',
    tags: ['HTML', 'CSS', 'JavaScript'],
    image: '/images/codepen.png',
    liveUrl: 'https://codepen.io/bbjdt2224',
    githubUrl: null,
  },
  {
    id: 'job-agent',
    title: 'Job Application AI Agent',
    description: 'An AI agent that automates and accelerates the job search process — parsing listings, tailoring resumes, and tracking applications. Part of the True Tech Team monorepo.',
    tags: ['AI', 'Python', 'React'],
    image: '/images/job-search.png',
    liveUrl: null,
    githubUrl: 'https://github.com/TrueTechTeam/true-tech-team/tree/master/packages/job-search',
  },
  {
    id: 'hotmess-sports',
    title: 'Hotmess Sports',
    description: 'A rec sports league management app — scheduling, standings, rosters, registration, and team communication. Built because I captain a kickball team.',
    tags: ['React', 'TypeScript', 'Node.js'],
    image: '/images/hotmess/IMG_3515.PNG',
    liveUrl: null,
    githubUrl: null,
  },
  {
    id: 'recipes-app',
    title: 'Recipes App',
    description: 'A test project built to learn how to write my first AI agent. Searches the web for recipes based on ingredients or keywords, tailored to your profile and preferences, and lets you save favorites to a digital cookbook.',
    tags: ['AI', 'React', 'Web Search'],
    image: null,
    liveUrl: null,
    githubUrl: 'https://github.com/TrueTechTeam/true-tech-team/tree/master/packages/recipes',
  },
  {
    id: 'templates',
    title: 'Website Template Library',
    description: 'A collection of responsive, beautiful website templates for personal, fitness, cooking, and business use — each available as a React component or standalone HTML.',
    tags: ['React', 'CSS', 'Templates'],
    image: null,
    liveUrl: '/templates',
    githubUrl: null,
    internal: true,
  },
]
